/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bravoLibSol from "./BravoLib.sol";
export type { bravoLibSol };
export type { IBravoCallee } from "./IBravoCallee";
export type { Logic } from "./Logic";
